namespace WebApplication1.Domain
{
    /// <summary>
    /// In-memory order book with price-time priority matching.
    /// - BUY orders sorted by price (descending) then by time (ascending)
    /// - SELL orders sorted by price (ascending) then by time (ascending)
    /// </summary>
    public class OrderBook
    {
        private readonly Dictionary<string, Order> _orderMap = new();
        private readonly SortedSet<Order> _buyOrders = new(new BuyOrderComparer());
        private readonly SortedSet<Order> _sellOrders = new(new SellOrderComparer());
        private readonly List<Fill> _fills = new();

        public IReadOnlyList<Fill> Fills => _fills.AsReadOnly();

        /// <summary>
        /// Add a new order to the book and attempt to match it.
        /// Returns list of fills generated by this order.
        /// </summary>
        public List<Fill> AddOrder(Order order)
        {
            if (_orderMap.ContainsKey(order.OrderId))
                throw new InvalidOperationException($"Order {order.OrderId} already exists");

            _orderMap[order.OrderId] = order;
            var fills = new List<Fill>();

            if (order.Side == OrderSide.BUY)
            {
                fills.AddRange(MatchBuyOrder(order));
                if (order.RemainingQuantity > 0)
                    _buyOrders.Add(order);
            }
            else
            {
                fills.AddRange(MatchSellOrder(order));
                if (order.RemainingQuantity > 0)
                    _sellOrders.Add(order);
            }

            _fills.AddRange(fills);
            return fills;
        }

        /// <summary>
        /// Cancel an existing order.
        /// </summary>
        public bool CancelOrder(string orderId)
        {
            if (!_orderMap.TryGetValue(orderId, out var order))
                return false;

            _orderMap.Remove(orderId);

            if (order.Side == OrderSide.BUY)
                _buyOrders.Remove(order);
            else
                _sellOrders.Remove(order);

            return true;
        }

        /// <summary>
        /// Modify an existing order (cancel and re-add with new parameters).
        /// </summary>
        public List<Fill> ModifyOrder(string orderId, long newQuantity, decimal newPrice)
        {
            if (!_orderMap.TryGetValue(orderId, out var order))
                throw new InvalidOperationException($"Order {orderId} not found");

            var side = order.Side;
            var fills = new List<Fill>();

            // Cancel the old order
            CancelOrder(orderId);

            // Create new order with modified parameters, preserving timestamp for priority
            var newOrder = new Order(orderId, side, newPrice, newQuantity, order.Timestamp);

            // Re-add with new parameters
            fills.AddRange(AddOrder(newOrder));
            return fills;
        }

        /// <summary>
        /// Get all orders on the buy side sorted by priority.
        /// </summary>
        public List<Order> GetBuyOrders() => _buyOrders.ToList();

        /// <summary>
        /// Get all orders on the sell side sorted by priority.
        /// </summary>
        public List<Order> GetSellOrders() => _sellOrders.ToList();

        /// <summary>
        /// Get an order by ID.
        /// </summary>
        public Order GetOrder(string orderId)
        {
            return _orderMap.TryGetValue(orderId, out var order) ? order : null;
        }

        public void PrintOrderBook()
        {
            Console.WriteLine("\n=== ORDER BOOK ===");
            Console.WriteLine("BUY SIDE (sorted by price desc, then time asc):");
            if (_buyOrders.Count == 0)
                Console.WriteLine("  (empty)");
            else
                foreach (var order in _buyOrders)
                    Console.WriteLine($"  {order}");

            Console.WriteLine("\nSELL SIDE (sorted by price asc, then time asc):");
            if (_sellOrders.Count == 0)
                Console.WriteLine("  (empty)");
            else
                foreach (var order in _sellOrders)
                    Console.WriteLine($"  {order}");
            Console.WriteLine("==================\n");
        }

        private List<Fill> MatchBuyOrder(Order buyOrder)
        {
            var fills = new List<Fill>();

            while (buyOrder.RemainingQuantity > 0 && _sellOrders.Count > 0)
            {
                var sellOrder = _sellOrders.Min;

                if (buyOrder.Price < sellOrder.Price)
                    break; // No match possible

                var fillQty = Math.Min(buyOrder.RemainingQuantity, sellOrder.RemainingQuantity);
                var fill = new Fill(buyOrder.OrderId, sellOrder.OrderId, sellOrder.Price, fillQty);

                buyOrder.FilledQuantity += fillQty;
                sellOrder.FilledQuantity += fillQty;

                fills.Add(fill);

                if (sellOrder.RemainingQuantity == 0)
                    _sellOrders.Remove(sellOrder);
            }

            return fills;
        }

        private List<Fill> MatchSellOrder(Order sellOrder)
        {
            var fills = new List<Fill>();

            while (sellOrder.RemainingQuantity > 0 && _buyOrders.Count > 0)
            {
                var buyOrder = _buyOrders.Max;

                if (sellOrder.Price > buyOrder.Price)
                    break; // No match possible

                var fillQty = Math.Min(sellOrder.RemainingQuantity, buyOrder.RemainingQuantity);
                var fill = new Fill(buyOrder.OrderId, sellOrder.OrderId, buyOrder.Price, fillQty);

                sellOrder.FilledQuantity += fillQty;
                buyOrder.FilledQuantity += fillQty;

                fills.Add(fill);

                if (buyOrder.RemainingQuantity == 0)
                    _buyOrders.Remove(buyOrder);
            }

            return fills;
        }

        private class BuyOrderComparer : IComparer<Order>
        {
            public int Compare(Order x, Order y)
            {
                // Higher price has priority
                int priceComparison = y.Price.CompareTo(x.Price);
                if (priceComparison != 0)
                    return priceComparison;

                // Earlier timestamp has priority (FIFO)
                return x.Timestamp.CompareTo(y.Timestamp);
            }
        }

        private class SellOrderComparer : IComparer<Order>
        {
            public int Compare(Order x, Order y)
            {
                // Lower price has priority
                int priceComparison = x.Price.CompareTo(y.Price);
                if (priceComparison != 0)
                    return priceComparison;

                // Earlier timestamp has priority (FIFO)
                return x.Timestamp.CompareTo(y.Timestamp);
            }
        }
    }
}
